<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snowflake.proto

namespace GPBMetadata;

class Snowflake
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad5020a0f736e6f77666c616b652e70726f746f1209736e6f77666c616b" .
            "6522200a0b4e6578745265717565737412110a0973657276696365496418" .
            "012001280322170a094e6578745265706c79120a0a026964180120012803" .
            "221a0a0c506172736552657175657374120a0a026964180120012803224f" .
            "0a0a50617273655265706c7912110a0974696d657374616d701801200128" .
            "03120e0a066e6f6465496418022001280312110a09736572766963654964" .
            "180320012803120b0a03736571180420012803327e0a09536e6f77666c61" .
            "6b6512360a044e65787412162e736e6f77666c616b652e4e657874526571" .
            "756573741a142e736e6f77666c616b652e4e6578745265706c7922001239" .
            "0a05506172736512172e736e6f77666c616b652e50617273655265717565" .
            "73741a152e736e6f77666c616b652e50617273655265706c79220042075a" .
            "0570726f746f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

